spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/friend
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update # 개발 환경에서는 `update` 사용
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true # ANSI 코드에 색을 나타낸다
        use_sql_comments: true # SQL 내부에 /* */ 주석 추가

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
        autoconfigure.web: TRACE
        validation: DEBUG
        converter: DEBUG
        hibernate.type.descriptor.sql.BasicBinder: TRACE # 바인딩 값 로그
        hibernate.SQL: debug
      springframework.data.mongodb.core.MongoTemplate: DEBUG # MongoDB 로그 설정

server:
  port: 8080 # 개발 서버 포트