file:
  upload:
    path: ${FILE_PATH}/resource/happy-friends/
    image: images
    video: videos

kakao:
  api:
    # REST API -> KAKAO_MAP_KEY
    map: ${KAKAO_MAP_KEY}

feature:
  my-service:
    enabled: false
spring:
  datasource:
    url: ${MARIADB}
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate # 운영 환경에서는 스키마 변경 방지

logging:
  level:
    root: INFO # 로그 레벨을 최소화
server:
  port: ${PORT} # 운영 서버 포트